server:
  port: 8080

spring:
  config:
    import: 
      - classpath:datasource.yml
  liquibase:
    enabled: true
    change-log: classpath:changelog/main.yml

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN:your_bot_token_here}
    id: ${TELEGRAM_BOT_ID:your_bot_id_here}
    username: ${TELEGRAM_BOT_USERNAME:your_bot_username_here}
    webhook-path: ${TELEGRAM_BOT_WEBHOOK_PATH:your_bot_url_here}
